
21:18:36 | console  Traceback (most recent call last):
  File "C:\Users\xxl3m\AppData\Local\Programs\Python\Python39\lib\site-packages\discord\ext\commands\bot.py", line 618, in _load_from_module_spec
    setup(self)
  File "E:\Code\PortalRadio\cogs\music.py", line 160, in setup
    bot.add_cog(Music(bot))
  File "E:\Code\PortalRadio\cogs\music.py", line 36, in __init__
    self.rules.start()
AttributeError: 'Music' object has no attribute 'rules'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\xxl3m\AppData\Local\Programs\Python\Python39\lib\site-packages\discord\ext\commands\core.py", line 85, in wrapped
    ret = await coro(*args, **kwargs)
  File "E:\Code\PortalRadio\cogs\useful.py", line 71, in reload
    self.bot.reload_extension(extension)
  File "C:\Users\xxl3m\AppData\Local\Programs\Python\Python39\lib\site-packages\discord\ext\commands\bot.py", line 738, in reload_extension
    self.load_extension(name)
  File "C:\Users\xxl3m\AppData\Local\Programs\Python\Python39\lib\site-packages\discord\ext\commands\bot.py", line 663, in load_extension
    self._load_from_module_spec(spec, name)
  File "C:\Users\xxl3m\AppData\Local\Programs\Python\Python39\lib\site-packages\discord\ext\commands\bot.py", line 623, in _load_from_module_spec
    raise errors.ExtensionFailed(key, e) from e
discord.ext.commands.errors.ExtensionFailed: Extension 'cogs.music' raised an error: AttributeError: 'Music' object has no attribute 'rules'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\xxl3m\AppData\Local\Programs\Python\Python39\lib\site-packages\discord\ext\commands\bot.py", line 902, in invoke
    await ctx.command.invoke(ctx)
  File "C:\Users\xxl3m\AppData\Local\Programs\Python\Python39\lib\site-packages\discord\ext\commands\core.py", line 864, in invoke
    await injected(*ctx.args, **ctx.kwargs)
  File "C:\Users\xxl3m\AppData\Local\Programs\Python\Python39\lib\site-packages\discord\ext\commands\core.py", line 94, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: ExtensionFailed: Extension 'cogs.music' raised an error: AttributeError: 'Music' object has no attribute 'rules'
